import React, { createContext, useContext, useEffect, useMemo, useRef, useState } from "react";
import { Link, NavLink, Route, Routes, useLocation, useNavigate, useParams, useSearchParams } from "react-router-dom";
import {
  ArrowRight, BarChart3, Bell, BookOpen, Camera, Check, ChevronDown, ChevronRight, CircleUserRound,
  Clock3, Compass, FileImage, Heart, Home as HomeIcon, ImagePlus, Languages, LayoutDashboard, MapPin,
  Menu, Mic, Package, Palette, Plus, Search, Settings, ShoppingBag, Sparkles, Star, Store, Trash2,
  Upload, UserRound, Users, Wand2, WalletCards, X, Instagram, Youtube, Facebook, Eye, Truck, Box,
  SlidersHorizontal, ShieldCheck, Play, Headphones, MessageCircle, Award, Leaf, RefreshCcw
} from "lucide-react";
import { locales, supportedLanguages } from "./locales";
import { artisanData, craftData, events, productData, regions, stories } from "./data/catalog";
import { addToCart, getAllProducts, getCart, getCustomProducts, getWishlist, normalizeProduct, removeFromCart, removeProduct, saveProduct, toggleWishlist } from "./services/productService";
import { detectVoiceProduct, generateProductDetails, screenSellerVerification, suggestPrice } from "./services/aiService";
import { analyzeProductImage } from "./services/imageAnalysisService";
import { recommendProducts, visualMatch } from "./services/recommendationService";
import { getNotifications, markNotificationsSeen } from "./services/notificationService";
import { getOrders, statuses, updateOrderStatus } from "./services/orderService";
import { readJSON, writeJSON } from "./utils/storage";

const LOGO = "/assets/kalaudaan-logo-lockup.jpg";
const FULL_LOGO = "/assets/kalaudaan-logo.jpg";
const DEFAULT_IMAGE = productData[0].image;
const OFFLINE_IMAGE = "/assets/offline-heritage.svg";
const VERIFICATION_KEY = "kalaudaan-seller-verification";
function getVerificationStatus() { return readJSON(VERIFICATION_KEY, { qualified: false, score: 0 }); }
function setVerificationStatus(status) { writeJSON(VERIFICATION_KEY, status); try { window.dispatchEvent(new CustomEvent("kalaudaan:verification", { detail: status })); } catch {} }

const craftKey = {
  "Pochampally Ikat": "pochampally", "Gadwal Handloom": "gadwal", "Mangalagiri Cotton": "mangalagiri", Kalamkari: "kalamkari",
  Terracotta: "terracotta", "Blue Pottery": "bluePottery", "Wood Carving": "woodCarving", Embroidery: "embroidery", "Basket Weaving": "basket", "Metal Craft": "metal",
  Pottery: "pottery", Handloom: "handloom", "Wood Craft": "woodcraft", Jewellery: "jewellery"
};
const regionKey = { Telangana: "telangana", "Andhra Pradesh": "andhraPradesh", Karnataka: "karnataka", Rajasthan: "rajasthan", Gujarat: "gujarat", "West Bengal": "westBengal", Odisha: "odisha", "Tamil Nadu": "tamilNadu", Kerala: "kerala" };
const occasionKey = { Weddings: "weddings", Festivals: "festivals", Gifts: "gifts", "Daily Wear": "dailyWear", "Home Decor": "homeDecor", Traditional: "traditional", "Corporate Gifts": "corporateGifts" };

function textFor(value, lang) { return typeof value === "object" ? (value?.[lang] || value?.en || "") : value || ""; }
function tContent(value, lang) { return textFor(value, lang); }
function titleOf(product, lang) { return textFor(product.title || product.name, lang); }
function regionOf(name, t) { return t(regionKey[name] || name); }
function craftOf(name, t) { return t(craftKey[name] || name); }
function localizedRaw(value, t, lang) {
  const keyMap = {
    "India":"india", "Product":"product", "Traditional handwork":"traditionalHandwork",
    "Cotton":"cotton", "Terracotta":"terracotta", "Brass":"brass", "Sheesham Wood":"sheeshamWood",
    "Indigo":"indigo", "Magenta":"magenta", "Gold":"gold", "Maroon":"maroon", "Cream":"cream", "Rust":"rust", "Earth":"earth", "Walnut":"walnut", "Amber":"amber", "Wine":"wine", "Antique Gold":"antiqueGold", "handloom":"handloom", "ikat":"ikat", "cotton":"cotton", "telangana":"telangana", "pottery":"pottery", "handmade":"handmade", "terracotta":"terracotta", "wood":"wood", "carving":"carving", "decor":"decor", "jewellery":"jewellery", "brass":"brass", "kalamkari":"kalamkari", "painting":"painting", "textile":"textile", "embroidery":"embroidery"
  };
  const k = keyMap[value];
  return k ? t(k) : textFor(value, lang);
}

const LangContext = createContext({
  lang: "en",
  setLang: () => {},
  t: (key) => locales.en?.[key] ?? key
});
function useLang() {
  return useContext(LangContext);
}
function LangProvider({ children }) {
  const [lang, setLang] = useState(() => { try { return localStorage.getItem("kalaudaan-language") || "en"; } catch { return "en"; } });
  const changeLang = (next) => { const safe = supportedLanguages.includes(next) ? next : "en"; setLang(safe); try { localStorage.setItem("kalaudaan-language", safe); } catch {} document.documentElement.lang = safe; };
  useEffect(() => { document.documentElement.lang = lang; }, [lang]);
  useEffect(() => { const onStorage = (e) => { if (e.key === "kalaudaan-language" && supportedLanguages.includes(e.newValue)) setLang(e.newValue); }; window.addEventListener("storage", onStorage); return () => window.removeEventListener("storage", onStorage); }, []);
  const value = useMemo(() => ({ lang, setLang: changeLang, t: (key) => locales[lang]?.[key] ?? locales.en[key] ?? ({ cotton: lang === "te" ? "పత్తి" : lang === "hi" ? "कपास" : "Cotton", terracotta: lang === "te" ? "టెర్రాకోట" : lang === "hi" ? "टेराकोटा" : "Terracotta", brass: lang === "te" ? "ఇత్తడి" : lang === "hi" ? "पीतल" : "Brass", sheeshamWood: lang === "te" ? "శీషం చెక్క" : lang === "hi" ? "शीशम लकड़ी" : "Sheesham Wood", indigo: lang === "te" ? "ఇండిగో" : lang === "hi" ? "इंडिगो" : "Indigo", magenta: lang === "te" ? "మెజెంటా" : lang === "hi" ? "मैजेंटा" : "Magenta", gold: lang === "te" ? "బంగారం" : lang === "hi" ? "सोना" : "Gold", maroon: lang === "te" ? "మెరూన్" : lang === "hi" ? "मैरून" : "Maroon", cream: lang === "te" ? "క్రీమ్" : lang === "hi" ? "क्रीम" : "Cream", rust: lang === "te" ? "తుప్పు రంగు" : lang === "hi" ? "जंग रंग" : "Rust", earth: lang === "te" ? "మట్టి రంగు" : lang === "hi" ? "मिट्टी" : "Earth", walnut: lang === "te" ? "వాల్‌నట్" : lang === "hi" ? "अखरोट" : "Walnut", amber: lang === "te" ? "అంబర్" : lang === "hi" ? "ऐंबर" : "Amber", wine: lang === "te" ? "వైన్" : lang === "hi" ? "वाइन" : "Wine", antiqueGold: lang === "te" ? "పురాతన బంగారం" : lang === "hi" ? "एंटीक गोल्ड" : "Antique Gold" })[key] ?? key }), [lang]);
  return <LangContext.Provider value={value}>{children}</LangContext.Provider>;
}

function useToast() {
  const [toast, setToast] = useState("");
  const timer = useRef(null);
  const show = (message) => { setToast(message); clearTimeout(timer.current); timer.current = setTimeout(() => setToast(""), 2400); };
  return { toast, show };
}

class ErrorBoundary extends React.Component {
  constructor(props) { super(props); this.state = { error: false }; }
  static getDerivedStateFromError() { return { error: true }; }
  render() { if (this.state.error) return <div className="error-screen"><ShieldCheck size={42}/><h1>{this.props.t?.("empty") || "Something went wrong"}</h1><button className="gold-btn" onClick={() => window.location.reload()}><RefreshCcw size={16}/> Reload</button></div>; return this.props.children; }
}

function LanguageSelector() {
  const { lang, setLang, t } = useLang();
  return <label className="lang-select"><Languages size={14}/><select aria-label={t("language")} value={lang} onChange={(e) => setLang(e.target.value)}><option value="en">{t("english")}</option><option value="te">{t("telugu")}</option><option value="hi">{t("hindi")}</option></select><ChevronDown size={12}/></label>;
}
function Logo({ small = false }) { const { t } = useLang(); return <Link to="/" className={`logo ${small ? "small" : ""}`} aria-label={t("brand")}><img src={LOGO} alt={t("brand")}/><span>{t("brand")}</span><small>{t("brandTag")}</small></Link>; }

function Header() {
  const { t } = useLang();
  const [open, setOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const [counts, setCounts] = useState(() => ({ wishlist: getWishlist().length, cart: getCart().reduce((n, p) => n + (p.qty || 1), 0) }));
  const location = useLocation();
  useEffect(() => { const fn = () => setScrolled(window.scrollY > 30); window.addEventListener("scroll", fn, { passive: true }); return () => window.removeEventListener("scroll", fn); }, []);
  useEffect(() => { const sync = () => setCounts({ wishlist: getWishlist().length, cart: getCart().reduce((n, p) => n + (p.qty || 1), 0) }); window.addEventListener("kalaudaan:cart-wishlist", sync); window.addEventListener("storage", sync); sync(); return () => { window.removeEventListener("kalaudaan:cart-wishlist", sync); window.removeEventListener("storage", sync); }; }, []);
  const nav = [["/", "home"], ["/explore", "explore"], ["/artisans", "artisans"], ["/heritage", "heritage"], ["/stories", "stories"], ["/impact", "impact"]];
  useEffect(() => setOpen(false), [location.pathname]);
  return <header className={`site-header ${scrolled ? "scrolled" : ""}`}><div className="nav-inner"><Logo/><button className="mobile-menu" aria-label={t("menu")} onClick={() => setOpen((v) => !v)}><Menu size={22}/></button><nav className={`main-nav ${open ? "open" : ""}`}>{nav.map(([to, key]) => <NavLink key={to} to={to} end={to === "/"}>{t(key)}</NavLink>)}</nav><div className="nav-actions"><Link className="nav-icon" to="/search" title={t("search")} aria-label={t("search")}><Search size={18}/></Link><Link className="nav-icon nav-count" to="/wishlist" title={t("wishlist")} aria-label={`${t("wishlist")} (${counts.wishlist})`}><Heart size={18}/>{counts.wishlist > 0 && <b>{counts.wishlist}</b>}</Link><Link className="nav-icon nav-count" to="/cart" title={t("cart")} aria-label={`${t("cart")} (${counts.cart})`}><ShoppingBag size={18}/>{counts.cart > 0 && <b>{counts.cart}</b>}</Link><LanguageSelector/><Link className="login-pill" to="/login">{t("login")}</Link></div></div></header>;
}
function Footer() { const { t } = useLang(); return <footer className="footer"><div className="footer-pattern"/><div className="footer-inner"><div className="footer-brand"><Logo small/><p>{t("futureTag")}</p><div className="socials"><a href="https://instagram.com" aria-label="Instagram" target="_blank" rel="noreferrer"><Instagram/></a><a href="https://youtube.com" aria-label="YouTube" target="_blank" rel="noreferrer"><Youtube/></a><a href="https://facebook.com" aria-label="Facebook" target="_blank" rel="noreferrer"><Facebook/></a></div></div><div><h3>{t("marketplace")}</h3><Link to="/explore">{t("explore")}</Link><Link to="/artisans">{t("artisans")}</Link><Link to="/heritage">{t("heritage")}</Link><Link to="/stories">{t("stories")}</Link><Link to="/impact">{t("impact")}</Link></div><div><h3>{t("seller")}</h3><Link to="/role">{t("sellYourCraft")}</Link><Link to="/seller/product-studio">{t("aiProductStudio")}</Link><Link to="/seller">{t("dashboard")}</Link></div><div><h3>{t("support")}</h3><Link to="/about">{t("about")}</Link><Link to="/help">{t("help")}</Link><Link to="/contact">{t("contact")}</Link><Link to="/privacy">{t("privacy")}</Link></div></div><div className="footer-bottom"><span>© 2026 {t("brand")}</span><span>{t("brandTag")}</span></div></footer>; }
function Shell({ children }) { return <><Header/>{children}<Footer/><Assistant/></>; }

function Reveal({ children, className = "" }) { const ref = useRef(null); const [visible, setVisible] = useState(false); useEffect(() => { const el = ref.current; if (!el) return; const obs = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) { setVisible(true); obs.disconnect(); } }, { threshold: .12 }); obs.observe(el); return () => obs.disconnect(); }, []); return <div ref={ref} className={`reveal ${visible ? "is-visible" : ""} ${className}`}>{children}</div>; }
function HeritageMotif({ side = "left" }) { return <div className={`motif motif-${side}`} aria-hidden="true"><span/><i/><b/><em/></div>; }

const heroImage = "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1800&q=88";
const loomImage = "https://images.unsplash.com/photo-1604323347240-1f1c1b1b3b13?auto=format&fit=crop&w=1200&q=88";
const potteryImage = "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=1200&q=88";
const artisanImage = "https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&w=1200&q=88";
const textileImage = "https://images.unsplash.com/photo-1583846717393-dc2412c95ed2?auto=format&fit=crop&w=1200&q=88";

function Home() {
  const { t, lang } = useLang(); const navigate = useNavigate();
  const editorial = [
    { eyebrow: "meetMakers", title: "theWeaver", text: "weaverText", image: loomImage, side: "left", facts: [["handloom", "handloom"], ["telangana", "telangana"], ["years25", "years25"], ["verifiedArtisan", "verifiedArtisan"]], cta: "meetWeaver", to: "/artisan/a2" },
    { eyebrow: "craftedByHands", title: "thePotter", text: "potterText", image: potteryImage, side: "right", facts: [["pottery", "pottery"], ["andhraPradesh", "andhraPradesh"], ["years20", "years20"], ["verifiedArtisan", "verifiedArtisan"]], cta: "explorePottery", to: "/explore?craft=Pottery" },
    { eyebrow: "heritageLivesHere", title: "theArtisan", text: "artisanText", image: artisanImage, side: "left", facts: [["handicrafts", "handicrafts"], ["karnataka", "karnataka"], ["years15", "years15"], ["verifiedArtisan", "verifiedArtisan"]], cta: "discoverArtisans", to: "/artisans" },
    { eyebrow: "traditionalWeaving", title: "theHandloom", text: "handloomText", image: textileImage, side: "right", facts: [["handloom", "handloom"], ["telangana", "telangana"], ["years25", "years25"], ["verifiedArtisan", "verifiedArtisan"]], cta: "shopHandloom", to: "/explore?craft=Handloom" }
  ];
  return <main className="home">
    <section className="hero-cinematic"><div className="hero-bg" style={{ backgroundImage: `url(${heroImage}), url(${OFFLINE_IMAGE})` }}/><div className="hero-overlay"/><HeritageMotif side="right"/><div className="hero-inner"><Reveal className="hero-copy"><div className="gold-kicker"><span/>{t("heroKicker")}</div><h1>{t("heroTitle1")}<br/>{t("heroTitle2")}<br/><em>{t("heroTitle3")}</em></h1><p>{t("heroText")}</p><div className="hero-ctas"><button className="gold-btn" onClick={() => navigate("/explore")}>{t("exploreCrafts")} <ArrowRight size={16}/></button><button className="line-btn" onClick={() => navigate("/artisans")}>{t("meetArtisans")} <ArrowRight size={16}/></button></div><div className="hero-points"><span>{t("supportArtisans")}</span><b>•</b><span>{t("preserveHeritage")}</span><b>•</b><span>{t("empowerCommunities")}</span></div></Reveal><div className="hero-art"><div className="hero-circle"><img src={heroImage} alt={t("meetArtisans")}/><div className="circle-ring ring1"/><div className="circle-ring ring2"/><div className="mandala">✦</div></div><div className="hero-note">{t("traditionEveryThread")}<span>✦</span></div></div></div></section>
    <section className="editorial-stack">{editorial.map((item, idx) => <EditorialSection key={item.title} item={item} index={idx} lang={lang}/>)}</section>
    <CraftShowcase/>
    <HeritageSection/>
    <AISection/>
    <VoiceSection/>
    <StorySection/>
    <BuyerAISection/>
    <ImpactSection/>
    <FinalCTA/>
  </main>;
}

function EditorialSection({ item, index, lang }) { const { t } = useLang(); const image = item.image; const extra = index === 0 ? ["https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=500&q=80", "https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=500&q=80"] : index === 1 ? ["https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=500&q=80", potteryImage] : [textileImage, loomImage];
  return <section className={`maker-section ${item.side === "right" ? "reverse" : ""}`}><div className="maker-bg" style={{ backgroundImage: `url(${image})` }}/><div className="maker-overlay"/><div className="maker-inner"><Reveal className="maker-visual"><div className="portrait-wrap"><div className="portrait-main"><img src={image} alt={t(item.title)}/></div><div className="portrait-small s1"><img src={extra[0]} alt=""/></div><div className="portrait-small s2"><img src={extra[1]} alt=""/></div><div className="portrait-rings"/></div></Reveal><Reveal className="maker-copy"><div className="gold-kicker"><span/>{t(item.eyebrow)}</div><h2>{t(item.title)}</h2><p>{t(item.text)}</p><button className="line-btn" onClick={() => window.history.pushState({}, "", item.to) || window.dispatchEvent(new PopStateEvent("popstate"))}>{t(item.cta)} <ArrowRight size={16}/></button></Reveal><div className="maker-facts">{item.facts.map(([icon, key]) => <div key={key}><span className="fact-icon"><Check size={14}/></span><span>{t(key)}</span></div>)}</div></div></section>;
}

function SectionTitle({ eyebrow, title, text, action }) { const { t } = useLang(); return <div className="section-title"><div><div className="gold-kicker"><span/>{t(eyebrow)}</div><h2>{t(title)}</h2>{text && <p>{t(text)}</p>}</div>{action}</div>; }

function StatsStrip() { const { t } = useLang(); const stats = [["12,450+", "artisansSupported"], ["38,200+", "productsListed"], ["18", "craftRegions"], ["42", "traditionalCrafts"]]; return <div className="impact-strip">{stats.map(([n, k]) => <div key={k}><span>{k === "artisansSupported" ? "♧" : k === "productsListed" ? "▣" : k === "craftRegions" ? "⌖" : "✿"}</span><strong>{n}</strong><small>{t(k)}</small></div>)}</div>; }

function CraftShowcase() { const { t, lang } = useLang(); const navigate = useNavigate(); return <section className="section dark-section crafts-showcase"><div className="container"><SectionTitle eyebrow="craftsOfIndia" title="craftsOfIndia" text="futureTag" action={<button className="line-btn" onClick={() => navigate("/explore")}>{t("exploreCrafts")} <ArrowRight size={15}/></button>}/><div className="craft-gallery">{craftData.map((c, i) => <button className={`craft-card c${i % 4}`} key={c.key} onClick={() => navigate(`/explore?craft=${encodeURIComponent(c.name)}`)}><img loading="lazy" src={c.image} alt={craftOf(c.name, t)}/><div className="craft-card-overlay"><small>{regionOf(c.region, t)}</small><h3>{craftOf(c.name, t)}</h3><p>{tContent(c.description, lang)}</p></div></button>)}</div></div></section>; }

function HeritageSection() { const { t } = useLang(); const [selected, setSelected] = useState(regions[0]); return <section className="heritage-section section"><div className="container"><SectionTitle eyebrow="discoverHeritage" title="discoverHeritage" text="futureTag"/><div className="heritage-layout"><div className="india-visual"><div className="india-map">{t("india")}<small>✦</small></div>{regions.map((r, i) => <button key={r.key} className={`map-dot d${i + 1} ${selected.key === r.key ? "active" : ""}`} onClick={() => setSelected(r)} aria-label={regionOf(r.name, t)}><span/></button>)}</div><div className="region-panel"><div className="gold-kicker"><span/>{t("selectRegion")}</div><h3>{regionOf(selected.name, t)}</h3><div className="region-meta"><span><Palette/> {t("crafts")}</span><span><Users/> {selected.artisans}</span><span><Package/> {selected.products}</span></div><div className="region-crafts">{selected.crafts.map(c => <button key={c} onClick={() => { const el = document.getElementById("explore"); if (el) el.scrollIntoView(); }}>{craftOf(c, t)}</button>)}</div><Link className="gold-btn" to={`/explore?region=${encodeURIComponent(selected.name)}`}>{t("exploreRegion")} <ArrowRight size={15}/></Link></div></div></div></section>; }

function AISection() { const { t } = useLang(); const navigate = useNavigate(); const cards = [["aiProductStudio", Wand2, "/seller/product-studio"], ["voiceToSell", Mic, "/seller/product-studio"], ["aiPriceAdvisor", WalletCards, "/seller/product-studio"], ["aiBuyerAssistant", MessageCircle, "/search"]]; return <section className="ai-transition section"><div className="ai-glow"/><div className="container"><SectionTitle eyebrow="traditionMeetsAI" title="traditionMeetsAI" text="futureTag"/><div className="ai-cards">{cards.map(([key, Icon, to]) => <button key={key} onClick={() => navigate(to)}><span className="ai-icon"><Icon/></span><small>{t("brandTag")}</small><h3>{t(key)}</h3><ArrowRight className="ai-arrow" size={18}/></button>)}</div></div></section>; }

function VoiceSection() { const { t, lang } = useLang(); const [text, setText] = useState(""); const [detected, setDetected] = useState(null); const [listening, setListening] = useState(false); const recognitionRef = useRef(null); const start = () => { const SR = window.SpeechRecognition || window.webkitSpeechRecognition; if (!SR) { setDetected({ error: t("voiceUnsupported") }); return; } try { const r = new SR(); r.lang = lang === "te" ? "te-IN" : lang === "hi" ? "hi-IN" : "en-IN"; r.interimResults = false; r.onstart = () => setListening(true); r.onend = () => setListening(false); r.onerror = () => { setListening(false); setDetected({ error: t("voiceDenied") }); }; r.onresult = (e) => { const value = e.results?.[0]?.[0]?.transcript || ""; setText(value); setDetected(detectVoiceProduct(value)); }; recognitionRef.current = r; r.start(); } catch { setDetected({ error: t("voiceDenied") }); } }; const stop = () => { try { recognitionRef.current?.stop(); } catch {} setListening(false); }; return <section className="voice-section section"><div className="container voice-layout"><div><div className="gold-kicker"><span/>{t("speakToSell")}</div><h2>{t("speakToSell")}</h2><p>{t("voiceStorefront")}</p><div className="voice-flow"><span>🎙</span><b>→</b><span>AI</span><b>→</b><span>{t("product")}</span></div><p className="voice-example">{t("speakExample")}</p></div><div className="voice-card"><div className="voice-card-top"><span className="pulse-mic"><Mic/></span><div><b>{t("voiceToSell")}</b><small>{t("speakToSellText")}</small></div></div><textarea value={text} onChange={(e) => { setText(e.target.value); setDetected(detectVoiceProduct(e.target.value)); }} placeholder={t("speakExample")} aria-label={t("description")}/><div className="voice-actions"><button className="gold-btn" onClick={listening ? stop : start}>{listening ? <><Clock3 size={15}/>{t("stopListening")}</> : <><Mic size={15}/>{t("speakNow")}</>}</button><button className="line-btn" onClick={() => { if (text) setDetected(detectVoiceProduct(text)); }}>{t("generate")}</button></div>{detected && !detected.error && <div className="detected"><h4>{t("detectedInfo")}</h4><div><span>{t("material")}</span><b>{detected.material}</b></div><div><span>{t("price")}</span><b>{detected.price ? `₹${Number(detected.price).toLocaleString("en-IN")}` : "—"}</b></div><div><span>{t("languageDetected")}</span><b>{detected.language}</b></div></div>}{detected?.error && <div className="inline-error">{detected.error}</div>}</div></div></section>; }

function StorySection() { const { t, lang } = useLang(); const navigate = useNavigate(); return <section className="section stories-home"><div className="container"><SectionTitle eyebrow="everyCraftStory" title="everyCraftStory" text="futureTag" action={<Link className="line-btn" to="/stories">{t("viewStory")} <ArrowRight size={15}/></Link>}/><div className="story-grid">{stories.map((s, i) => <article className={`story-card story-${i}`} key={s.id}><img loading="lazy" src={s.image} alt={tContent(s.title, lang)}/><div><small>{t(s.type === "watch" ? "watchStory" : s.type === "listen" ? "listenStory" : "readStory")}</small><h3>{tContent(s.title, lang)}</h3><p>{tContent(s.text, lang)}</p><button onClick={() => navigate("/stories")}>{t("viewStory")} <ArrowRight size={14}/></button></div></article>)}</div></div></section>; }

function BuyerAISection() { const { t, lang } = useLang(); const [q, setQ] = useState(""); const [results, setResults] = useState([]); const products = getAllProducts(); const run = () => setResults(recommendProducts(products, q, { wishlist: getWishlist(), viewed: readJSON("kalaudaan-viewed", []) })); return <section className="buyer-ai section"><div className="container buyer-ai-inner"><div><div className="gold-kicker"><span/>{t("aiBuyerAssistant")}</div><h2>{t("findMeaningful")}</h2><p>{t("assistantReply")}</p><div className="assistant-search"><MessageCircle size={17}/><input value={q} onChange={(e) => setQ(e.target.value)} onKeyDown={(e) => e.key === "Enter" && run()} placeholder={t("assistantPlaceholder")}/><button onClick={run}><ArrowRight size={17}/></button></div></div><div className="assistant-results">{(results.length ? results : products.slice(0, 2)).map((p) => <MiniProduct key={p.id} product={p}/>)}</div></div></section>; }

function ImpactSection() { const { t } = useLang(); return <section className="impact-home section"><div className="impact-bg"/><div className="container"><div className="impact-copy"><div className="gold-kicker"><span/>{t("preservingHeritage")}</div><h2>{t("preservingHeritage")}</h2><p>{t("futureTag")}</p></div><StatsStrip/></div></section>; }
function FinalCTA() { const { t } = useLang(); return <section className="final-cta"><div className="final-bg"/><div className="final-overlay"/><div className="final-inner"><div className="gold-kicker"><span/>{t("futureHeritage")}</div><h2>{t("futureHeritage")}</h2><p>{t("finalText")}</p><div><Link className="gold-btn" to="/explore">{t("exploreCrafts")} <ArrowRight size={15}/></Link><Link className="line-btn" to="/role">{t("becomeArtisan")} <ArrowRight size={15}/></Link></div></div></section>; }

function SearchBar({ onSearch }) { const { t, lang } = useLang(); const [q, setQ] = useState(""); const [image, setImage] = useState(""); const [voiceError, setVoiceError] = useState(""); const recognition = useRef(null); const doSearch = (value = q) => onSearch(value, image); const voice = () => { const SR = window.SpeechRecognition || window.webkitSpeechRecognition; if (!SR) { setVoiceError(t("voiceUnsupported")); return; } try { const r = new SR(); r.lang = lang === "te" ? "te-IN" : lang === "hi" ? "hi-IN" : "en-IN"; r.onresult = (e) => { const value = e.results?.[0]?.[0]?.transcript || ""; setQ(value); doSearch(value); }; r.onerror = () => setVoiceError(t("voiceDenied")); recognition.current = r; r.start(); } catch { setVoiceError(t("voiceDenied")); } }; const file = (e) => { const f = e.target.files?.[0]; if (!f) return; if (!f.type.startsWith("image/") || f.size > 5 * 1024 * 1024) { setVoiceError(t("fileError")); e.target.value = ""; return; } const reader = new FileReader(); reader.onload = () => { setImage(String(reader.result)); setVoiceError(""); }; reader.onerror = () => setVoiceError(t("fileError")); reader.readAsDataURL(f); }; return <div className="searchbar"><Search size={18}/><input value={q} onChange={(e) => setQ(e.target.value)} onKeyDown={(e) => e.key === "Enter" && doSearch()} placeholder={t("searchPlaceholder")} aria-label={t("search")}/><button className="search-action" onClick={voice} title={t("voiceSearch")}><Mic size={17}/></button><label className="search-action" title={t("searchByImage")}><ImagePlus size={17}/><input hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={file}/></label><button className="search-submit" onClick={() => doSearch()}><ArrowRight size={17}/></button>{image && <button className="search-clear" onClick={() => { setImage(""); }}><X size={15}/></button>}{voiceError && <span className="search-error">{voiceError}</span>}</div>; }

function Explore() { const { t, lang } = useLang(); const [params] = useSearchParams(); const initialCraft = params.get("craft") || ""; const initialRegion = params.get("region") || ""; const [query, setQuery] = useState(""); const [image, setImage] = useState(""); const [craft, setCraft] = useState(initialCraft); const [region, setRegion] = useState(initialRegion); const [occasion, setOccasion] = useState(""); const products = getAllProducts(); const filtered = products.filter((p) => { const q = query.toLowerCase(); return (!q || `${titleOf(p, lang)} ${p.craft} ${p.region} ${(p.tags || []).join(" ")}`.toLowerCase().includes(q)) && (!craft || p.craft.toLowerCase().includes(craft.toLowerCase()) || titleOf(p, lang).toLowerCase().includes(craft.toLowerCase())) && (!region || p.region === region) && (!occasion || (p.occasion || []).includes(occasion)); }); const search = (q, img) => { setQuery(q); setImage(img); if (img) { const name = q || "image"; const matches = visualMatch(products, name); setQuery(matches.map((p) => p.craft).join(" ")); } }; const setOcc = (v) => setOccasion((x) => x === v ? "" : v); return <main className="page dark-page"><div className="container"><div className="page-head cinematic-head"><div><div className="gold-kicker"><span/>{t("craftsOfIndia")}</div><h1>{t("explore")}</h1><p>{t("futureTag")}</p></div><Link className="gold-btn" to="/heritage">{t("heritage")} <ArrowRight size={15}/></Link></div><SearchBar onSearch={search}/>{image && <div className="image-search-note"><FileImage size={16}/>{t("imageSearchHint")}<button onClick={() => setImage("")}>{t("clear")}</button></div>}<div className="filter-block"><div className="filter-title"><SlidersHorizontal size={15}/><b>{t("shopByOccasion")}</b></div><div className="chips">{Object.keys(occasionKey).map((o) => <button className={occasion === o ? "chip active" : "chip"} key={o} onClick={() => setOcc(o)}>{t(occasionKey[o])}</button>)}</div><div className="filter-selects"><select value={craft} onChange={(e) => setCraft(e.target.value)} aria-label={t("craft")}><option value="">{t("all")}</option>{craftData.map((c) => <option key={c.name} value={c.name}>{craftOf(c.name, t)}</option>)}</select><select value={region} onChange={(e) => setRegion(e.target.value)} aria-label={t("region")}><option value="">{t("all")}</option>{regions.map((r) => <option key={r.name} value={r.name}>{regionOf(r.name, t)}</option>)}</select></div></div><div className="section-title compact"><div><div className="gold-kicker"><span/>{t("recommended")}</div><h2>{t("searchResults")}</h2></div><small>{filtered.length} / {products.length}</small></div>{filtered.length ? <ProductGrid products={filtered}/> : <EmptyState text={t("noProducts")} to="/explore"/>}</div></main>; }

function ProductGrid({ products }) { return <div className="product-grid-premium">{products.map((p) => <ProductCard key={p.id} product={p}/>)}</div>; }
function ProductCard({ product }) { const { t, lang } = useLang(); const [wished, setWished] = useState(() => getWishlist().includes(product.id)); const { toast, show } = useToast(); const navigate = useNavigate(); const add = () => { addToCart(product); show(t("addedCart")); }; const wish = () => { const next = toggleWishlist(product.id); setWished(next.includes(product.id)); show(next.includes(product.id) ? t("addedWishlist") : t("removedWishlist")); }; return <article className="product-card-premium"><button className={`heart-btn ${wished ? "on" : ""}`} onClick={wish} aria-label={wished ? t("remove") : t("wishlist")}><Heart size={17} fill={wished ? "currentColor" : "none"}/></button><button className="product-image-btn" onClick={() => { const viewed = readJSON("kalaudaan-viewed", []); writeJSON("kalaudaan-viewed", [...new Set([product.id, ...viewed])].slice(0, 20)); navigate(`/product/${product.id}`); }}><img loading="lazy" src={product.image || DEFAULT_IMAGE} alt={titleOf(product, lang)}/><span className="verified-badge"><Check size={11}/>{t("verifiedArtisan")}</span></button><div className="product-info"><small>{craftOf(product.craft, t)} • {regionOf(product.region, t)}</small><h3>{titleOf(product, lang)}</h3><div className="rating"><Star size={13} fill="currentColor"/> {product.rating}</div><div className="product-bottom"><strong>₹{Number(product.price || 0).toLocaleString("en-IN")}</strong><button className="mini-gold" onClick={add}><Plus size={14}/>{t("addToCart")}</button></div></div>{toast && <div className="toast">{toast}</div>}</article>; }
function MiniProduct({ product }) { const { t, lang } = useLang(); return <Link className="mini-product" to={`/product/${product.id}`}><img src={product.image} alt={titleOf(product, lang)}/><span><small>{craftOf(product.craft, t)}</small><b>{titleOf(product, lang)}</b><strong>₹{product.price.toLocaleString("en-IN")}</strong></span><ChevronRight size={15}/></Link>; }
function EmptyState({ text, to }) { const { t } = useLang(); return <div className="empty-state"><Package size={34}/><h3>{text}</h3><Link className="gold-btn" to={to}>{t("exploreCrafts")} <ArrowRight size={15}/></Link></div>; }

function ProductDetails() {
  const { id } = useParams();
  const { t, lang } = useLang();
  const navigate = useNavigate();
  const rawProduct = getAllProducts().find((p) => p.id === id);
  const product = normalizeProduct(rawProduct || {});
  const [qty, setQty] = useState(1);
  const [galleryImage, setGalleryImage] = useState(rawProduct?.image || DEFAULT_IMAGE);
  if (!rawProduct) return <NotFound/>;
  const artisan = artisanData.find((a) => a.id === product.artisanId) || artisanData[0];
  const isCustom = getCustomProducts().some((p) => p.id === product.id);
  const add = () => { for (let i = 0; i < qty; i += 1) addToCart(product); alert(t("addedCart")); };
  const buyNow = () => { addToCart(product); navigate("/cart"); };
  return <main className="page dark-page"><div className="container detail-page">
    <Link className="back-link" to="/explore">← {t("back")}</Link>
    <div className="market-product-layout">
      <div className="market-gallery"><div className="gallery-main"><img src={galleryImage} alt={titleOf(product, lang)}/><span className="verified-badge"><Check size={11}/>{t("verifiedArtisan")}</span></div><div className="gallery-thumbs"><button className="thumb active" onClick={() => setGalleryImage(product.image || DEFAULT_IMAGE)} aria-label={t("productGallery")}><img src={product.image || DEFAULT_IMAGE} alt={t("productGallery")}/></button><button className="thumb" onClick={() => setGalleryImage(product.image || DEFAULT_IMAGE)} aria-label={t("productGallery")}><img src={product.image || DEFAULT_IMAGE} alt={t("productGallery")}/></button><button className="thumb" onClick={() => setGalleryImage(product.image || DEFAULT_IMAGE)} aria-label={t("productGallery")}><img src={product.image || DEFAULT_IMAGE} alt={t("productGallery")}/></button></div></div>
      <div className="market-product-copy"><div className="gold-kicker"><span/>{craftOf(product.craft, t)} • {regionOf(product.region, t)}</div><h1>{titleOf(product, lang)}</h1><div className="market-rating"><span><Star size={14} fill="currentColor"/> {product.rating || 5}</span><small>{t("profileVerified")}</small></div><div className="market-price">₹{Number(product.price || 0).toLocaleString("en-IN")}</div><p className="market-note">{t("priceEstimate")}</p><div className="offer-box"><strong>{t("offers")}</strong><span>✦ {t("securePurchase")}</span><span>✦ {t("returnPolicy")}</span></div><div className="delivery-box"><Truck size={18}/><div><b>{t("delivery")}</b><small>{t("deliveryInfo")}</small></div></div><div className="quantity-row"><b>{t("selectQuantity")}</b><div className="quantity-control"><button onClick={() => setQty(Math.max(1, qty - 1))} aria-label="Decrease quantity">−</button><span>{qty}</span><button onClick={() => setQty(qty + 1)} aria-label="Increase quantity">+</button></div><span className="stock-ok">✓ {t("available")}</span></div><div className="detail-actions market-actions"><button className="gold-btn" onClick={add}><ShoppingBag size={16}/>{t("addToCart")}</button><button className="line-btn" onClick={buyNow}>{t("buyNow")} <ArrowRight size={15}/></button>{isCustom && <button className="line-btn" onClick={() => navigate(`/seller/product-studio?edit=${product.id}`)}><Settings size={15}/>{t("editProduct")}</button>}</div><div className="seller-mini"><img src={artisan.image} alt={artisan.name}/><div><small>{t("soldBy")}</small><h3>{artisan.name}</h3><p>{artisan.craft} • {regionOf(artisan.region, t)} • {artisan.experience}</p><Link to={`/artisan/${artisan.id}`}>{t("viewArtisan")} <ArrowRight size={13}/></Link></div><Check size={20}/></div></div>
    </div>
    <div className="product-detail-panels"><section><div className="panel-kicker">{t("aboutProduct")}</div><h2>{t("details")}</h2><p>{textFor(product.description, lang)}</p><div className="detail-spec-grid"><div><small>{t("category")}</small><b>{craftOf(product.craft, t)}</b></div><div><small>{t("material")}</small><b>{localizedRaw(textFor(product.material, lang), t, lang)}</b></div><div><small>{t("region")}</small><b>{regionOf(product.region, t)}</b></div><div><small>{t("colors")}</small><b>{Array.isArray(product.colors) ? product.colors.map(c => localizedRaw(c, t, lang)).join(", ") : localizedRaw(product.colors, t, lang)}</b></div></div></section><section><div className="panel-kicker">{t("highlights")}</div><h2>{t("craftStory")}</h2><p>{textFor(artisan.story, lang)}</p><div className="detail-tags">{(Array.isArray(product.tags) ? product.tags : []).map((tag) => <span key={String(tag)}>#{localizedRaw(String(tag), t, lang)}</span>)}</div></section></div>
    <section className="meet-maker-large"><div className="meet-maker-photo"><img src={artisan.image} alt={artisan.name}/></div><div><div className="gold-kicker"><span/>{t("meetMaker")}</div><h2>{t("sellerInfo")}</h2><h3>{artisan.name}</h3><p>{artisan.craft} • {regionOf(artisan.region, t)} • {artisan.experience}</p><span className="verified-line"><Check size={13}/>{t("profileVerified")}</span><blockquote>“{textFor(artisan.story, lang)}”</blockquote><Link className="line-btn" to={`/artisan/${artisan.id}`}>{t("viewArtisan")} <ArrowRight size={15}/></Link></div></section>
    <section className="reviews-panel"><div><div className="panel-kicker">{t("reviews")}</div><h2>{product.rating || 5}.0 / 5</h2><p>{t("futureTag")}</p></div><div className="review-bars"><span>5 ★ <i/></span><span>4 ★ <i style={{width:"30%"}}/></span><span>3 ★ <i style={{width:"12%"}}/></span></div></section>
  </div></main>;
}
function Artisans() { const { t, lang } = useLang(); return <main className="page dark-page"><div className="container"><SectionTitle eyebrow="artisans" title="meetArtisans" text="futureTag"/><div className="artisan-grid">{artisanData.map((a) => <article className="artisan-card" key={a.id}><div className="artisan-img"><img src={a.image} alt={a.name}/><span><Check size={12}/>{t("profileVerified")}</span></div><div><small>{a.craft} • {regionOf(a.region, t)}</small><h2>{a.name}</h2><p>{textFor(a.story, lang)}</p><div><span><Clock3 size={13}/>{a.experience}</span><Link to={`/artisan/${a.id}`}>{t("viewArtisan")} <ArrowRight size={14}/></Link></div></div></article>)}</div></div></main>; }
function ArtisanProfile() { const { id } = useParams(); const { t, lang } = useLang(); const a = artisanData.find((x) => x.id === id) || artisanData[0]; const products = getAllProducts().filter((p) => p.artisanId === a.id); return <main className="page dark-page"><div className="container profile-page"><Link className="back-link" to="/artisans">← {t("back")}</Link><div className="artisan-hero"><div className="artisan-profile-photo"><img src={a.image} alt={a.name}/><div className="profile-ring"/></div><div><div className="gold-kicker"><span/>{t("meetMaker")}</div><h1>{a.name}</h1><p>{a.craft} • {regionOf(a.region, t)} • {a.experience}</p><span className="verified-line"><Check size={13}/>{t("profileVerified")}</span><blockquote>“{textFor(a.story, lang)}”</blockquote><button className="line-btn" onClick={() => alert(t("messageSent"))}>{t("contactArtisan")} <ArrowRight size={15}/></button></div></div><SectionTitle eyebrow="craftsOfIndia" title="products"/><ProductGrid products={products}/></div></main>; }

function Heritage() { const { t } = useLang(); const [selected, setSelected] = useState(regions[0]); return <main className="page dark-page"><div className="container"><SectionTitle eyebrow="heritage" title="discoverHeritage" text="futureTag"/><div className="heritage-page"><div className="heritage-list">{regions.map((r) => <button key={r.key} className={selected.key === r.key ? "region-btn active" : "region-btn"} onClick={() => setSelected(r)}><span>{regionOf(r.name, t)}</span><small>{r.artisans} {t("artisans")} • {r.products} {t("productsListed")}</small></button>)}</div><div className="heritage-detail"><div className="heritage-map-large"><div className="india-map">{t("india")}<small>✦</small></div></div><div><div className="gold-kicker"><span/>{t("selectRegion")}</div><h2>{regionOf(selected.name, t)}</h2><p>{t("futureTag")}</p><div className="heritage-stat-row"><b>{selected.artisans}<small>{t("artisans")}</small></b><b>{selected.products}<small>{t("productsListed")}</small></b></div><h3>{t("traditionalTechniques")}</h3><div className="detail-tags">{selected.crafts.map(c => <span key={c}>{craftOf(c, t)}</span>)}</div><Link className="gold-btn" to={`/explore?region=${encodeURIComponent(selected.name)}`}>{t("exploreRegion")} <ArrowRight size={15}/></Link></div></div></div></div></main>; }

function Stories() { const { t, lang } = useLang(); return <main className="page dark-page"><div className="container"><SectionTitle eyebrow="stories" title="everyCraftStory" text="futureTag"/><div className="story-list">{stories.map((s) => <article key={s.id}><img loading="lazy" src={s.image} alt={tContent(s.title, lang)}/><div><div className="gold-kicker"><span/>{t(s.type === "watch" ? "watchStory" : s.type === "listen" ? "listenStory" : "readStory")}</div><h2>{tContent(s.title, lang)}</h2><p>{tContent(s.text, lang)}</p><div className="story-actions"><button onClick={() => alert(t("readMore"))}>{t("viewStory")} <ArrowRight size={14}/></button>{s.type === "watch" && <button><Play size={14}/>{t("watchStory")}</button>}{s.type === "listen" && <button><Headphones size={14}/>{t("listenStory")}</button>}</div></div></article>)}</div></div></main>; }

function Impact() { const { t } = useLang(); return <main className="page dark-page"><div className="container"><SectionTitle eyebrow="impact" title="preservingHeritage" text="futureTag"/><StatsStrip/><div className="impact-grid"><article><Award/><h2>{t("artisansSupported")}</h2><p>{t("futureTag")}</p></article><article><Leaf/><h2>{t("traditionalCrafts")}</h2><p>{t("futureTag")}</p></article><article><Users/><h2>{t("craftRegions")}</h2><p>{t("futureTag")}</p></article></div><div className="demo-note"><span>{t("demoData")}</span></div></div></main>; }

function Login() { const { t } = useLang(); const navigate = useNavigate(); const [form, setForm] = useState({ email: "", password: "" }); const [error, setError] = useState(""); const submit = (e) => { e.preventDefault(); if (!form.email.trim() || !form.password.trim()) { setError(t("required")); return; } writeJSON("kalaudaan-session", { email: form.email }); navigate("/role"); }; return <main className="auth-page"><div className="auth-visual" style={{ backgroundImage: `url(${heroImage}), url(${OFFLINE_IMAGE})` }}><div><div className="gold-kicker"><span/>{t("brandTag")}</div><h2>{t("preservingHeritage")}</h2></div></div><form className="auth-card" onSubmit={submit}><Logo small/><div className="gold-kicker"><span/>{t("loginTitle")}</div><h1>{t("loginTitle")}</h1><p>{t("loginNote")}</p><label>{t("email")}<input value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>{t("password")}<input type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })}/></label>{error && <div className="inline-error">{error}</div>}<button className="gold-btn" type="submit">{t("continue")} <ArrowRight size={15}/></button><small>{t("noAccount")} <Link to="/role">{t("createAccount")}</Link></small></form></main>; }
function Role() { const { t } = useLang(); return <main className="auth-page"><div className="auth-visual" style={{ backgroundImage: `url(${textileImage}), url(${OFFLINE_IMAGE})` }}><div><div className="gold-kicker"><span/>{t("brandTag")}</div><h2>{t("futureHeritage")}</h2></div></div><div className="auth-card role-card"><Logo small/><div className="gold-kicker"><span/>{t("roleTitle")}</div><h1>{t("roleTitle")}</h1><div className="role-grid"><Link to="/seller"><UserRound/><b>{t("joinSeller")}</b><small>{t("sellerPitch")}</small></Link><Link to="/explore"><ShoppingBag/><b>{t("shopBuyer")}</b><small>{t("buyerPitch")}</small></Link></div></div></main>; }

function SellerLayout({ children, active }) { const { t } = useLang(); const [open, setOpen] = useState(false); const items = [["dashboard", "/seller", LayoutDashboard], ["products", "/seller/products", Package], ["sellerOrders", "/seller/orders", Truck], ["inventory", "/seller/inventory", Box], ["productStudio", "/seller/product-studio", Wand2], ["photoStudio", "/seller/photo-studio", ImagePlus], ["analytics", "/seller/analytics", BarChart3], ["enquiries", "/seller/enquiries", Bell], ["market", "/seller/market", Compass], ["profile", "/seller/profile", UserRound], ["settings", "/seller/settings", Settings], ["verification", "/seller/verification", ShieldCheck]]; return <main className="seller-shell"><aside className={`seller-sidebar ${open ? "open" : ""}`}><div className="seller-head"><Logo small/><button onClick={() => setOpen(false)}><X size={18}/></button></div>{items.map(([key, to, Icon]) => <NavLink key={to} to={to} className={active === key ? "seller-link active" : "seller-link"} onClick={() => setOpen(false)}><Icon size={17}/><span>{t(key)}</span></NavLink>)}<Link className="seller-link logout" to="/"><ArrowRight size={17}/><span>{t("logout")}</span></Link></aside><button className="seller-open" onClick={() => setOpen(true)}><Menu/></button><section className="seller-content">{children}</section></main>; }
function SellerHeader({ title, eyebrow = "sellerDashboard" }) { const { t } = useLang(); return <div className="seller-top"><div><div className="gold-kicker"><span/>{t(eyebrow)}</div><h1>{t(title)}</h1></div><Link className="gold-btn" to="/seller/product-studio"><Plus size={15}/>{t("productStudio")}</Link></div>; }
function SellerDashboard() { const { t } = useLang(); const custom = getCustomProducts(); const wishlistCount = getWishlist().length; return <SellerLayout active="dashboard"><SellerHeader title="sellerDashboard"/><div className="seller-profile-banner"><div><span className="verified-line"><Check size={13}/>{t("profileVerified")}</span><h2>Ramesh Kumar</h2><p>{t("handloom")} • {t("telangana")}</p></div><Link className="line-btn" to="/seller/profile">{t("edit")} <ArrowRight size={15}/></Link></div><div className="seller-stats">{[[t("totalProducts"), 12 + custom.length, Package], [t("orderCount"), getOrders().length, ShoppingBag], [t("revenue"), "₹48,600", WalletCards], [t("productViews"), "2,450", Eye], [t("wishlistCount"), wishlistCount, Heart], [t("conversion"), "4.8%", BarChart3]].map(([label, value, Icon]) => <div key={label}><Icon/><small>{label}</small><strong>{value}</strong></div>)}</div><div className="seller-panel"><div><div className="gold-kicker"><span/>{t("aiInsights")}</div><h2>{t("aiInsights")}</h2><div className="insights">{["insight1", "insight2", "insight3"].map(k => <p key={k}><Sparkles size={15}/>{t(k)}</p>)}</div></div><div className="seller-mini-chart"><span style={{ height: "35%" }}/><span style={{ height: "55%" }}/><span style={{ height: "45%" }}/><span style={{ height: "70%" }}/><span style={{ height: "60%" }}/><span style={{ height: "88%" }}/></div></div><div className="seller-quick"><Link to="/seller/product-studio"><Wand2/><b>{t("productStudio")}</b></Link><Link to="/seller/photo-studio"><ImagePlus/><b>{t("photoStudio")}</b></Link><Link to="/seller/orders"><Truck/><b>{t("sellerOrders")}</b></Link><Link to="/seller/analytics"><BarChart3/><b>{t("analytics")}</b></Link></div></SellerLayout>; }

function ProductStudio() {
  const { t, lang } = useLang();
  const navigate = useNavigate();
  const [params] = useSearchParams();
  const editId = params.get("edit");
  const existing = editId ? getCustomProducts().find((p) => p.id === editId) : null;
  const useImproved = params.get("useImproved") === "1";
  const improvedImage = useImproved ? readJSON("kalaudaan-improved-image", "") : "";
  const blankForm = { name: "", craft: "", material: "", price: "", description: "", region: "", colors: "", stock: "", technique: "", tags: "", keywords: "", occasions: "" };
  const [form, setForm] = useState(() => existing ? {
    name: titleOf(existing, lang), craft: existing.craft || "", material: existing.material || "", price: String(existing.price || ""),
    description: textFor(existing.description, lang), region: existing.region || "", colors: Array.isArray(existing.colors) ? existing.colors.join(", ") : (existing.colors || ""),
    stock: String(existing.stock || ""), technique: existing.technique || "", tags: Array.isArray(existing.tags) ? existing.tags.join(", ") : (existing.tags || ""),
    keywords: Array.isArray(existing.keywords) ? existing.keywords.join(", ") : (existing.keywords || ""), occasions: Array.isArray(existing.occasion) ? existing.occasion.join(", ") : ""
  } : blankForm);
  const [image, setImage] = useState(existing?.image || improvedImage || "");
  const [imageFileName, setImageFileName] = useState("");
  const [imageAnalysis, setImageAnalysis] = useState(null);
  const [preview, setPreview] = useState(existing ? { title: titleOf(existing, lang), description: textFor(existing.description, lang), category: existing.craft, materials: existing.material, colors: existing.colors, tags: existing.tags || [], keywords: existing.keywords || [], suggestedRange: "—", occasions: existing.occasion || [] } : null);
  const [msg, setMsg] = useState("");
  const [busy, setBusy] = useState(false);
  const [cameraOpen, setCameraOpen] = useState(false);
  const [error, setError] = useState("");
  const [verification, setVerification] = useState(getVerificationStatus());
  const [voiceText, setVoiceText] = useState("");
  const [listening, setListening] = useState(false);
  const recognitionRef = useRef(null);
  useEffect(() => { const sync = () => setVerification(getVerificationStatus()); window.addEventListener("kalaudaan:verification", sync); return () => window.removeEventListener("kalaudaan:verification", sync); }, []);
  const update = (key, value) => setForm((f) => ({ ...f, [key]: value }));
  const onFile = (e) => { const file = e.target.files?.[0]; if (!file) return; if (!file.type.startsWith("image/") || file.size > 5 * 1024 * 1024) { setError(t("fileError")); e.target.value = ""; return; } const r = new FileReader(); r.onload = async () => { const dataUrl = String(r.result || ""); setImage(dataUrl); setImageFileName(file.name); setImageAnalysis(await analyzeProductImage(file, dataUrl)); setError(""); setPreview(null); }; r.onerror = () => setError(t("fileError")); r.readAsDataURL(file); e.target.value = ""; };
  const startVoice = () => { const SR = window.SpeechRecognition || window.webkitSpeechRecognition; if (!SR) { setError(t("voiceUnsupported")); return; } try { const r = new SR(); r.lang = lang === "te" ? "te-IN" : lang === "hi" ? "hi-IN" : "en-IN"; r.interimResults = false; r.onstart = () => setListening(true); r.onend = () => setListening(false); r.onerror = () => { setListening(false); setError(t("voiceDenied")); }; r.onresult = (e) => { const value = e.results?.[0]?.[0]?.transcript || ""; setVoiceText(value); setError(""); }; recognitionRef.current = r; r.start(); } catch { setListening(false); setError(t("voiceDenied")); } };
  const generate = () => {
    if (!image) { setError(t("uploadBeforeGenerate")); return; }
    setBusy(true); setError("");
    window.setTimeout(async () => {
      try {
        const analysis = imageAnalysis || await analyzeProductImage({ name: imageFileName, type: "image/*", size: 0 }, image);
        const hint = voiceText.trim();
        const detected = detectVoiceProduct(hint);
        const material = detected.material !== "Handmade" ? detected.material : analysis.material;
        const price = detected.price || "";
        const craft = analysis.craft || "Handloom";
        const region = analysis.region || "Telangana";
        const seed = { ...blankForm, material, price, description: hint, craft, region, colors: analysis.dominantColor, imageAnalysis: analysis };
        const data = generateProductDetails(seed, lang);
        const fallbackPrice = analysis.craft === "Pottery" ? "1299" : analysis.craft === "Jewellery" ? "1099" : "1799";
        const next = { ...blankForm, name: data.title, craft: data.category, material: data.materials, price: price || fallbackPrice, description: data.description, region, colors: data.colors, stock: "10", technique: "Traditional handwork", tags: data.tags.join(", "), keywords: data.keywords.join(", "), occasions: data.occasions.join(", ") };
        setForm(next); setPreview({ ...data, imageAnalysis: analysis }); setImageAnalysis(analysis); setBusy(false);
      } catch { setBusy(false); setError(t("imageAnalysisError")); }
    }, 450);
  };
  const save = () => {
    if (!verification.qualified) { setError(t("publishLocked")); return; }
    if (!preview) { setError(t("generateBeforePublish")); return; }
    if (!image || !form.name.trim() || !form.material.trim() || !form.price || Number(form.price) <= 0) { setError(t("required")); return; }
    const generated = { en: generateProductDetails(form, "en"), te: generateProductDetails(form, "te"), hi: generateProductDetails(form, "hi") };
    const product = { id: editId || `custom-${Date.now()}`, title: { en: generated.en.title, te: generated.te.title, hi: generated.hi.title }, description: { en: generated.en.description, te: generated.te.description, hi: generated.hi.description }, price: Number(form.price), craft: form.craft, region: form.region, material: form.material, colors: form.colors.split(",").map(s => s.trim()).filter(Boolean), tags: (form.tags || "handmade").split(",").map(s => s.trim()).filter(Boolean), keywords: (form.keywords || "").split(",").map(s => s.trim()).filter(Boolean), occasion: (form.occasions || "Weddings, Festivals, Gifts").split(",").map(s => s.trim()).filter(Boolean), stock: Number(form.stock) || 1, rating: existing?.rating || 5, artisanId: existing?.artisanId || "a2", image, technique: form.technique, verification: { qualified: true, score: verification.score, method: "KalaUdaan AI Verification Assistant" } };
    saveProduct(product); setMsg(editId ? t("productUpdated") : t("productPublished")); setTimeout(() => navigate("/seller/products"), 650);
  };
  return <SellerLayout active="productStudio">
    <div className="seller-top"><div><div className="gold-kicker"><span/>{t("aiProductStudio")}</div><h1>{editId ? t("editProduct") : t("aiProductStudio")}</h1><p>{editId ? t("editHint") : t("studioImageFirst")}</p></div></div>
    <div className="studio-steps"><span>01 {t("upload")}</span><span>02 {t("generate")}</span><span>03 {t("preview")}</span><span>04 {t("publish")}</span></div>
    <div className={`verification-gate ${verification.qualified ? "passed" : "pending"}`}><div><div className="gold-kicker"><span/><ShieldCheck size={14}/>{t("verificationAssistant")}</div><h2>{verification.qualified ? t("verificationQualified") : t("verificationPending")}</h2><p>{t("verificationNote")}</p></div><div className="verification-gate-actions">{verification.qualified ? <span className="verified-line"><Check size={14}/>{t("verificationPassed")} • {verification.score}%</span> : <Link className="line-btn" to="/seller/verification">{t("openVerification")} <ArrowRight size={14}/></Link>}</div></div>
    <div className="studio-grid">
      <div className="studio-media"><UploadBox image={image} onFile={onFile} onCamera={() => setCameraOpen(true)} onRemove={() => { setImage(""); setImageFileName(""); setImageAnalysis(null); setPreview(null); }} />
        <div className="speak-sell-mini"><div><b>{t("speakToSell")}</b><small>{t("voiceToSellText")}</small></div><button className="line-btn" onClick={listening ? () => { try { recognitionRef.current?.stop(); } catch {} setListening(false); } : startVoice}>{listening ? t("stopListening") : t("speakNow")}</button></div>
        {voiceText && <div className="voice-transcript"><b>{t("detectedInfo")}</b><span>{voiceText}</span></div>}
        <button className="gold-btn full" disabled={busy || !image} onClick={generate}>{busy ? <><Clock3 size={15}/>{t("analyzingImage")}</> : <><Wand2 size={15}/>{t("generateProduct")}</>}</button>
        <small className="prototype-note">{t("localAIPrototype")}</small>{error && <div className="inline-error">{error}</div>}
      </div>
      {preview ? (
        <div className="studio-form">
          <div className="generated-lock"><Check size={15}/>{t("aiFieldsGenerated")}</div>
          {preview?.imageAnalysis && <div className="image-analysis-strip"><b>{t("visualAnalysis")}</b><span>{t("detectedCraft")}: {preview.imageAnalysis.craft}</span><span>{t("detectedColor")}: {preview.imageAnalysis.dominantColor}</span><span>{t("imageSize")}: {preview.imageAnalysis.width} × {preview.imageAnalysis.height}</span></div>}
          <div className="form-grid">
            <Field label={t("productTitle")} value={form.name} onChange={(v) => update("name", v)} required />
            <Field label={t("category")} value={form.craft} onChange={(v) => update("craft", v)} select options={["Handloom", "Pottery", "Wood Craft", "Jewellery", "Kalamkari", "Embroidery"]} />
            <Field label={t("material")} value={form.material} onChange={(v) => update("material", v)} required />
            <Field label={t("price")} value={form.price} onChange={(v) => update("price", v)} type="number" required />
            <Field label={t("region")} value={form.region} onChange={(v) => update("region", v)} select options={regions.map((r) => r.name)} />
            <Field label={t("stock")} value={form.stock} onChange={(v) => update("stock", v)} type="number" />
            <Field label={t("colors")} value={form.colors} onChange={(v) => update("colors", v)} />
            <Field label={t("craftTechnique") || t("techniques")} value={form.technique} onChange={(v) => update("technique", v)} />
          </div>
          <Field label={t("description")} value={form.description} onChange={(v) => update("description", v)} textarea />
          <div className="form-actions">
            <button className="line-btn" onClick={() => navigate("/seller/products")}>{t("cancel")}</button>
            <button className="gold-btn" disabled={busy || !verification.qualified || !preview} onClick={save} title={!verification.qualified ? t("publishLocked") : t("publish")}>
              {editId ? t("applyEdit") : t("publish")} <ArrowRight size={15} />
            </button>
          </div>
          {msg && <div className="success-note">{msg}</div>}
        </div>
      ) : (
        <div className="studio-empty"><Wand2 size={38}/><h2>{t("generateToFill")}</h2><p>{t("generateToFillText")}</p></div>
      )}
    </div>
    {preview && <div className="ai-preview"><div className="gold-kicker"><span/>{t("aiGenerated")}</div><div className="preview-grid"><PreviewItem label={t("productTitle")} value={preview.title}/><PreviewItem label={t("description")} value={preview.description}/><PreviewItem label={t("category")} value={preview.category}/><PreviewItem label={t("material")} value={preview.materials}/><PreviewItem label={t("colors")} value={preview.colors}/><PreviewItem label={t("tags")} value={Array.isArray(preview.tags) ? preview.tags.join(", ") : preview.tags}/><PreviewItem label={t("keywords")} value={Array.isArray(preview.keywords) ? preview.keywords.join(", ") : preview.keywords}/><PreviewItem label={t("suggestedPrice")} value={preview.suggestedRange}/></div><p className="disclaimer">{t("priceDisclaimer")}</p></div>}
    {cameraOpen && <CameraModal onClose={() => setCameraOpen(false)} onCapture={(data) => { setImage(data); setPreview(null); setCameraOpen(false); }}/>}</SellerLayout>;
}
function UploadBox({ image, onFile, onCamera, onRemove }) { const { t } = useLang(); return <div className="upload-box">{image ? <div className="upload-preview"><img src={image} alt={t("preview")}/><div><button onClick={onRemove}><Trash2 size={14}/>{t("remove")}</button><label><Upload size={14}/>{t("replace")}<input hidden type="file" accept="image/*" onChange={onFile}/></label></div></div> : <><div className="upload-icon"><ImagePlus size={28}/></div><b>{t("uploadPhoto")}</b><small>JPG • PNG • WEBP • 5 MB</small><div className="upload-actions"><label><Upload size={14}/>{t("gallery")}<input hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={onFile}/></label><button onClick={onCamera}><Camera size={14}/>{t("camera")}</button></div></>}</div>; }
function CameraModal({ onClose, onCapture }) { const { t } = useLang(); const videoRef = useRef(null); const streamRef = useRef(null); const [error, setError] = useState(""); useEffect(() => { let mounted = true; if (!navigator.mediaDevices?.getUserMedia) { setError(t("voiceUnsupported")); return () => {}; } navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" }, audio: false }).then(s => { if (!mounted) { s.getTracks().forEach(tr => tr.stop()); return; } streamRef.current = s; if (videoRef.current) videoRef.current.srcObject = s; }).catch(() => setError(t("voiceDenied"))); return () => { mounted = false; streamRef.current?.getTracks().forEach(tr => tr.stop()); }; }, [t]); const capture = () => { const video = videoRef.current; if (!video) return; const canvas = document.createElement("canvas"); canvas.width = video.videoWidth || 800; canvas.height = video.videoHeight || 600; canvas.getContext("2d")?.drawImage(video, 0, 0, canvas.width, canvas.height); onCapture(canvas.toDataURL("image/jpeg", .86)); }; return <div className="modal-backdrop"><div className="camera-modal"><button className="modal-close" onClick={onClose}><X/></button><video ref={videoRef} autoPlay playsInline/><div>{error ? <div className="inline-error">{error}</div> : <button className="gold-btn" onClick={capture}><Camera size={16}/>{t("preview")}</button>}<button className="line-btn" onClick={onClose}>{t("cancel")}</button></div></div></div>; }
function Field({ label, value, onChange, textarea = false, select = false, options = [], type = "text", required = false }) { const { t, lang } = useLang(); const optionLabel = (o) => craftKey[o] ? craftOf(o, t) : regionKey[o] ? regionOf(o, t) : localizedRaw(o, t, lang); return <label className="field"><span>{label}{required && <sup>*</sup>}</span>{textarea ? <textarea value={value} onChange={(e) => onChange(e.target.value)} rows={5} /> : select ? <select value={value} onChange={(e) => onChange(e.target.value)}>{options.map(o => <option key={o} value={o}>{optionLabel(o)}</option>)}</select> : <input type={type} value={value} onChange={(e) => onChange(e.target.value)} aria-label={label}/>}<small>{required ? t("required") : " "}</small></label>; }
function PreviewItem({ label, value }) { return <div><small>{label}</small><p>{value}</p></div>; }

function SellerProducts() { const { t, lang } = useLang(); const [products, setProducts] = useState(getCustomProducts()); const refresh = () => setProducts(getCustomProducts()); const del = (id) => { removeProduct(id); refresh(); }; return <SellerLayout active="products"><SellerHeader title="products"/><div className="seller-product-list">{products.length ? products.map(p => <div className="seller-product-row" key={p.id}><img src={p.image || DEFAULT_IMAGE} alt={titleOf(p, lang)}/><div><b>{titleOf(p, lang)}</b><small>{craftOf(p.craft, t)} • ₹{p.price.toLocaleString("en-IN")}</small></div><Link className="line-btn" to={`/product/${p.id}`}>{t("viewDetails")}</Link><button className="icon-danger" onClick={() => del(p.id)} aria-label={t("delete")}><Trash2 size={16}/></button></div>) : <EmptyState text={t("noProducts")} to="/seller/product-studio"/>}</div><div className="seller-note">{t("productsListed")} • {products.length}</div></SellerLayout>; }
function SellerOrders() { const { t } = useLang(); const [orders, setOrders] = useState(getOrders()); const [selected, setSelected] = useState(null); const update = (id, status) => setOrders(updateOrderStatus(id, status)); return <SellerLayout active="sellerOrders"><SellerHeader title="sellerOrders"/><div className="order-list">{orders.map(o => <article key={o.id} className="order-row"><div className="order-status"><span className={`status-dot ${o.status.toLowerCase()}`}/><b>{t(o.status.toLowerCase())}</b></div><div><strong>{o.productName}</strong><small>{o.id} • {o.customer}</small></div><span>₹{o.price.toLocaleString("en-IN")}</span><button className="line-btn" onClick={() => setSelected(o)}>{t("viewOrder")}</button><select value={o.status} onChange={(e) => update(o.id, e.target.value)} aria-label={t("updateStatus")}>{statuses.map(s => <option key={s}>{s}</option>)}</select></article>)}</div>{selected && <div className="modal-backdrop" onClick={() => setSelected(null)}><div className="detail-modal" onClick={(e) => e.stopPropagation()}><button className="modal-close" onClick={() => setSelected(null)}><X/></button><div className="gold-kicker"><span/>{t("viewOrder")}</div><h2>{selected.productName}</h2><p><b>{t("customer")}:</b> {selected.customer}</p><p><b>{t("orderDate")}:</b> {selected.date}</p><p><b>{t("estimatedDelivery")}:</b> {selected.delivery}</p><p><b>{t("updateStatus")}:</b> {t(selected.status.toLowerCase())}</p></div></div>}</SellerLayout>; }
function Inventory() { const { t, lang } = useLang(); const products = getAllProducts(); return <SellerLayout active="inventory"><SellerHeader title="inventory"/><div className="inventory-grid">{products.map(p => <article key={p.id}><img src={p.image} alt={titleOf(p, lang)}/><div><b>{titleOf(p, lang)}</b><small>{t("stock")}: {p.stock}</small><div className="stock-bar"><span style={{ width: `${Math.min(100, (p.stock / 20) * 100)}%` }}/></div></div></article>)}</div></SellerLayout>; }
function Analytics() { const { t } = useLang(); return <SellerLayout active="analytics"><SellerHeader title="analytics"/><div className="seller-stats">{[[t("revenue"), "₹48,600", WalletCards], [t("productViews"), "2,450", Eye], [t("conversion"), "4.8%", BarChart3]].map(([l, v, I]) => <div key={l}><I/><small>{l}</small><strong>{v}</strong></div>)}</div><div className="analytics-panel"><div className="analytics-bars">{[40, 62, 55, 78, 68, 88, 74, 96, 82, 100].map((h, i) => <span style={{ height: `${h}%` }} key={i}/>)}</div><div className="insights">{["insight1", "insight2", "insight3"].map(k => <p key={k}><Sparkles size={15}/>{t(k)}</p>)}</div></div><div className="demo-note">{t("demoData")}</div></SellerLayout>; }
function PhotoStudio() {
  const { t } = useLang(); const navigate = useNavigate();
  const [image, setImage] = useState(""); const [improved, setImproved] = useState(""); const [brightness, setBrightness] = useState(100); const [contrast, setContrast] = useState(105); const [saturation, setSaturation] = useState(105); const [warmth, setWarmth] = useState(0); const [crop, setCrop] = useState(false); const [cleanup, setCleanup] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const onFile = (e) => { const f = e.target.files?.[0]; if (!f) return; if (!f.type.startsWith("image/") || f.size > 5 * 1024 * 1024) { setError(t("fileError")); e.target.value = ""; return; } const r = new FileReader(); r.onload = () => { setImage(String(r.result || "")); setImproved(""); setError(""); }; r.onerror = () => setError(t("fileError")); r.readAsDataURL(f); e.target.value = ""; };
  const filterStyle = { filter: `brightness(${brightness}%) contrast(${contrast}%) saturate(${saturation}%) sepia(${warmth}%)`, objectFit: crop ? "cover" : "contain" };
  const makeImproved = () => { if (!image) return; setBusy(true); setError(""); const img = new Image(); img.onload = () => { try { const max=1200, scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)); const w=Math.max(1,Math.round(img.naturalWidth*scale)), h=Math.max(1,Math.round(img.naturalHeight*scale)); const side=Math.min(w,h); const canvas=document.createElement("canvas"); canvas.width=crop?side:w; canvas.height=crop?side:h; const ctx=canvas.getContext("2d"); if(!ctx) throw new Error("canvas"); const sx=crop?Math.max(0,(w-side)/2):0, sy=crop?Math.max(0,(h-side)/2):0; ctx.filter=`brightness(${brightness}%) contrast(${contrast}%) saturate(${saturation}%) sepia(${warmth}%)`; ctx.drawImage(img,sx,sy,canvas.width,canvas.height,0,0,canvas.width,canvas.height); const out=canvas.toDataURL("image/jpeg",.9); setImproved(out); writeJSON("kalaudaan-improved-image",out); } catch { setError(t("photoProcessError")); } finally { setBusy(false); } }; img.onerror=()=>{setBusy(false);setError(t("photoProcessError"));}; img.src=image; };
  const useImage = (src) => { if (!src) return; writeJSON("kalaudaan-improved-image", src); navigate("/seller/product-studio?useImproved=1"); };
  const reset = () => { setBrightness(100); setContrast(105); setSaturation(105); setWarmth(0); setCrop(false); setCleanup(false); setImproved(""); };
  return <SellerLayout active="photoStudio"><SellerHeader title="photoStudio"/><div className="photo-studio-head"><div><div className="gold-kicker"><span/>{t("photoStudioTools")}</div><p>{t("photoStudioText")}</p></div></div><div className="photo-studio">
    <div className="photo-card"><div className="photo-card-head"><div className="gold-kicker"><span/>{t("original")}</div>{image && <button className="line-btn compact" onClick={() => useImage(image)}>{t("useOriginalImage")}</button>}</div>{image ? <div className="photo-stage"><img src={image} alt={t("original")}/></div> : <div className="photo-placeholder"><ImagePlus size={30}/><label className="gold-btn">{t("upload")}<input hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={onFile}/></label><small>{t("photoUploadHint")}</small></div>}{image && <div className="photo-under-actions"><label className="line-btn compact">{t("replace")}<input hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={onFile}/></label><button className="line-btn compact" onClick={()=>{setImage("");setImproved("");}}>{t("remove")}</button></div>}</div>
    <div className="photo-card"><div className="photo-card-head"><div className="gold-kicker"><span/>{t("improved")}</div>{improved && <button className="line-btn compact" onClick={() => useImage(improved)}>{t("useInProductStudio")}</button>}</div>{image ? <div className={`photo-preview-frame ${cleanup ? "cleanup" : ""}`}><img style={filterStyle} src={improved || image} alt={t("improved")}/></div> : <div className="photo-placeholder"><Wand2 size={30}/><p>{t("photoNote")}</p></div>}<div className="photo-controls"><label>{t("brightness")}<input aria-label={t("brightness")} type="range" min="70" max="130" value={brightness} onChange={(e)=>{setBrightness(Number(e.target.value));setImproved("")}}/></label><label>{t("contrast")}<input aria-label={t("contrast")} type="range" min="80" max="140" value={contrast} onChange={(e)=>{setContrast(Number(e.target.value));setImproved("")}}/></label><label>{t("saturation")}<input aria-label={t("saturation")} type="range" min="70" max="140" value={saturation} onChange={(e)=>{setSaturation(Number(e.target.value));setImproved("")}}/></label><label>{t("warmth")}<input aria-label={t("warmth")} type="range" min="0" max="30" value={warmth} onChange={(e)=>{setWarmth(Number(e.target.value));setImproved("")}}/></label><div className="photo-toggle-row"><button className={crop ? "line-btn active" : "line-btn"} onClick={()=>{setCrop(v=>!v);setImproved("")}}>{t("cropCenter")}</button><button className={cleanup ? "line-btn active" : "line-btn"} onClick={()=>setCleanup(v=>!v)}>{t("backgroundCleanup")}</button><button className="line-btn" onClick={reset}>{t("resetEdits")}</button></div><div className="photo-actions"><button className="gold-btn" disabled={!image || busy} onClick={makeImproved}><Wand2 size={15}/>{busy ? t("processingImage") : t("createImproved")}</button>{improved && <button className="line-btn" onClick={()=>useImage(improved)}>{t("useInProductStudio")} <ArrowRight size={14}/></button>}</div>{error && <div className="inline-error">{error}</div>}</div></div>
  </div><div className="demo-note">{t("photoStudioDisclaimer")}</div></SellerLayout>;
}

function SellerAnalyticsPlaceholder({ active, title, icon = Sparkles }) { const { t } = useLang(); const Icon = icon; return <SellerLayout active={active}><SellerHeader title={title}/><div className="placeholder-panel"><Icon size={38}/><h2>{t(title)}</h2><p>{t("futureTag")}</p><Link className="gold-btn" to="/seller/product-studio">{t("aiProductStudio")} <ArrowRight size={15}/></Link></div></SellerLayout>; }
function Profile() { const { t } = useLang(); const [name, setName] = useState("Ramesh Kumar"); const [phone, setPhone] = useState("+91 9XXXXXXXXX"); const [email, setEmail] = useState("artisan@example.com"); const [saved, setSaved] = useState(false); return <SellerLayout active="profile"><SellerHeader title="profile"/><div className="form-card-large"><Field label={t("name")} value={name} onChange={setName}/><Field label={t("phone")} value={phone} onChange={setPhone}/><Field label={t("email")} value={email} onChange={setEmail}/><button className="gold-btn" onClick={() => { writeJSON("kalaudaan-profile", { name, phone, email }); setSaved(true); }}>{t("saveChanges")}</button>{saved && <div className="success-note">{t("profileSaved")}</div>}</div></SellerLayout>; }
function SettingsPage() { const { t } = useLang(); const [saved, setSaved] = useState(false); return <SellerLayout active="settings"><SellerHeader title="settings"/><div className="settings-panel"><label><input type="checkbox" defaultChecked/> {t("notification")}</label><label><input type="checkbox" defaultChecked/> {t("futureTag")}</label><button className="gold-btn" onClick={() => setSaved(true)}>{t("saveChanges")}</button>{saved && <div className="success-note">{t("settingsSaved")}</div>}</div></SellerLayout>; }
function Verification() {
  const { t } = useLang();
  const [form, setForm] = useState({ name: "Ramesh Kumar", craft: "Handloom Weaver", region: "Telangana", experience: "25", documentName: "" });
  const [result, setResult] = useState(getVerificationStatus()); const [error, setError] = useState("");
  const onDoc = (e) => { const f = e.target.files?.[0]; if (!f) return; const allowed = ["image/png", "image/jpeg", "image/webp", "application/pdf"]; if (!allowed.includes(f.type) || f.size > 5 * 1024 * 1024) { setError(t("fileError")); e.target.value = ""; return; } setForm((x) => ({ ...x, documentName: f.name })); setError(""); };
  const run = () => { const checked = screenSellerVerification(form); setResult(checked); setVerificationStatus(checked); if (!checked.qualified) setError(t("verificationIncomplete")); else setError(""); };
  return <SellerLayout active="verification"><SellerHeader title="verification"/><div className="verification-assistant-page"><div className="verification-intro"><div className="verification-orb"><ShieldCheck size={42}/></div><div><div className="gold-kicker"><span/>{t("verificationAssistant")}</div><h2>{result.qualified ? t("verificationQualified") : t("verificationPending")}</h2><p>{t("verificationIntro")}</p><small>{t("verificationNote")}</small></div></div><div className="verification-form-grid"><Field label={t("sellerName")} value={form.name} onChange={(v) => setForm({ ...form, name: v })} required/><Field label={t("craft")} value={form.craft} onChange={(v) => setForm({ ...form, craft: v })} required/><Field label={t("region")} value={form.region} onChange={(v) => setForm({ ...form, region: v })} select options={regions.map(r => r.name)}/><Field label={t("experienceYears")} value={form.experience} onChange={(v) => setForm({ ...form, experience: v })} type="number" required/><label className="field"><span>{t("identityDocument")}<sup>*</sup></span><label className="document-picker"><Upload size={15}/>{form.documentName || t("chooseDocument")}<input hidden type="file" accept="image/png,image/jpeg,image/webp,application/pdf" onChange={onDoc}/></label><small>{t("required")}</small></label></div>{error && <div className="inline-error">{error}</div>}<div className="verification-run"><button className="gold-btn" onClick={run}><ShieldCheck size={16}/>{t("runVerification")}</button>{result.score > 0 && <div className={result.qualified ? "verification-result qualified" : "verification-result"}><b>{result.qualified ? t("verificationQualified") : t("verificationFailed")}</b><span>{t("verificationScore")}: {result.score}%</span>{result.checks?.map((c) => <small key={c.key}>{c.pass ? "✓" : "○"} {t(c.label)}</small>)}</div>}</div>{result.qualified && <div className="success-note"><Check size={15}/>{t("verificationComplete")}</div>}</div></SellerLayout>;
}
function Notifications() { const { t, lang } = useLang(); const [items, setItems] = useState(getNotifications()); return <main className="page dark-page"><div className="container"><SectionTitle eyebrow="notifications" title="notifications" text="futureTag" action={<button className="line-btn" onClick={() => setItems(markNotificationsSeen())}>{t("markRead")} <Check size={14}/></button>}/><div className="notification-list">{items.map(n => <article key={n.id} className={n.seen ? "seen" : ""}><Bell/><div><b>{textFor(n.title, lang)}</b><p>{textFor(n.text, lang)}</p></div><small>{n.time}</small></article>)}</div></div></main>; }
function Wishlist() { const { t } = useLang(); const [ids, setIds] = useState(getWishlist()); useEffect(() => { const sync = () => setIds(getWishlist()); window.addEventListener("kalaudaan:cart-wishlist", sync); return () => window.removeEventListener("kalaudaan:cart-wishlist", sync); }, []); const products = getAllProducts().filter(p => ids.includes(p.id)); return <main className="page dark-page"><div className="container"><SectionTitle eyebrow="wishlist" title="wishlistTitle" text="futureTag"/>{products.length ? <ProductGrid products={products}/> : <EmptyState text={t("empty")} to="/explore"/>}</div></main>; }
function Cart() { const { t, lang } = useLang(); const [cart, setCart] = useState(getCart()); const total = cart.reduce((s, p) => s + Number(p.price || 0) * (p.qty || 1), 0); return <main className="page dark-page"><div className="container"><SectionTitle eyebrow="cart" title="cartTitle" text="futureTag"/>{cart.length ? <div className="cart-layout"><div className="cart-items">{cart.map(p => <div className="cart-row" key={p.id}><img src={p.image} alt={titleOf(p, lang)}/><div><b>{titleOf(p, lang)}</b><small>{p.qty || 1} × ₹{p.price.toLocaleString("en-IN")}</small></div><button onClick={() => setCart(removeFromCart(p.id))}><Trash2 size={16}/></button></div>)}</div><aside className="cart-summary"><small>{t("total")}</small><strong>₹{total.toLocaleString("en-IN")}</strong><button className="gold-btn" onClick={() => alert(t("demoCheckout"))}>{t("checkout")} <ArrowRight size={15}/></button></aside></div> : <EmptyState text={t("empty")} to="/explore"/>}</div></main>; }
function BuyerOrders() { const { t } = useLang(); const orders = getOrders(); return <main className="page dark-page"><div className="container"><SectionTitle eyebrow="orders" title="ordersTitle" text="futureTag"/><div className="buyer-orders">{orders.map(o => <article key={o.id}><div><span className={`status-pill ${o.status.toLowerCase()}`}>{t(o.status.toLowerCase())}</span><h3>{o.productName}</h3><small>{o.id} • {o.date}</small></div><div><b>₹{o.price.toLocaleString("en-IN")}</b><small>{t("estimatedDelivery")}: {o.delivery}</small></div></article>)}</div></div></main>; }
function Rewards() { const { t } = useLang(); const [points, setPoints] = useState(() => readJSON("kalaudaan-points", 120)); const earn = () => { const next = points + 25; setPoints(next); writeJSON("kalaudaan-points", next); }; return <main className="page dark-page"><div className="container"><SectionTitle eyebrow="rewards" title="rewards" text="earnPoints"/><div className="points-card"><Award/><strong>{points}</strong><span>{t("points")}</span><p>{t("earnPoints")}</p><button className="gold-btn" onClick={earn}>+25 {t("points")}</button></div></div></main>; }
function About() { const { t } = useLang(); return <main className="page dark-page"><div className="container about-page"><img src={FULL_LOGO} alt={t("brand")}/><div><SectionTitle eyebrow="about" title="futureHeritage" text="futureTag"/><p>{t("heroText")}</p></div></div></main>; }
function SimplePage({ title }) { const { t } = useLang(); return <main className="page dark-page"><div className="container"><SectionTitle eyebrow={title} title={title} text="futureTag"/><div className="placeholder-panel"><Sparkles size={38}/><h2>{t(title)}</h2><p>{t("futureTag")}</p></div></div></main>; }
function Events() { const { t, lang } = useLang(); const [filter, setFilter] = useState("all"); const [selected, setSelected] = useState(null); const list = events.filter(e => filter === "all" || e.type === filter); return <main className="page dark-page"><div className="container"><SectionTitle eyebrow="event" title="event" text="futureTag"/><div className="chips"><button className={filter === "all" ? "chip active" : "chip"} onClick={() => setFilter("all")}>{t("all")}</button><button className={filter === "exhibition" ? "chip active" : "chip"} onClick={() => setFilter("exhibition")}>{t("exhibition")}</button><button className={filter === "workshop" ? "chip active" : "chip"} onClick={() => setFilter("workshop")}>{t("workshop")}</button></div><div className="event-grid">{list.map(e => <article key={e.id}><img src={e.image} alt={textFor(e.title, lang)}/><div><small>{t(e.type)}</small><h2>{textFor(e.title, lang)}</h2><p>{textFor(e.detail, lang)}</p><span><CalendarDaysIcon/> {e.date} • {e.venue}</span><button className="line-btn" onClick={() => setSelected(e)}>{t("viewDetails")} <ArrowRight size={14}/></button></div></article>)}</div></div>{selected && <div className="modal-backdrop" onClick={() => setSelected(null)}><div className="event-modal" onClick={e => e.stopPropagation()}><button className="modal-close" onClick={() => setSelected(null)}><X/></button><img src={selected.image} alt={textFor(selected.title, lang)}/><div><div className="gold-kicker"><span/>{t(selected.type)}</div><h2>{textFor(selected.title, lang)}</h2><p>{textFor(selected.detail, lang)}</p><p><b>{t("date")}:</b> {selected.date}<br/><b>{t("venue")}:</b> {selected.venue}</p><button className="gold-btn" onClick={() => { alert(t("registerSuccess")); setSelected(null); }}>{t("register")} <ArrowRight size={15}/></button></div></div></div>}</main>; }
function CalendarDaysIcon() { return <Clock3 size={14}/>; }
function NotFound() { const { t } = useLang(); return <main className="page dark-page"><div className="container"><div className="not-found"><h1>404</h1><p>{t("notFound")}</p><Link className="gold-btn" to="/">{t("goHome")} <ArrowRight size={15}/></Link></div></div></main>; }

function Assistant() { const { t } = useLang(); const [open, setOpen] = useState(false); const [q, setQ] = useState(""); const [results, setResults] = useState([]); const run = () => setResults(recommendProducts(getAllProducts(), q, { wishlist: getWishlist(), viewed: readJSON("kalaudaan-viewed", []) })); return <div className={`floating-assistant ${open ? "open" : ""}`}><button className="assistant-toggle" onClick={() => setOpen(v => !v)} aria-label={t("askAI")}><Sparkles size={19}/></button>{open && <div className="assistant-pop"><div><b>{t("askAI")}</b><button onClick={() => setOpen(false)}><X size={15}/></button></div><p>{t("assistantReply")}</p><input value={q} onChange={e => setQ(e.target.value)} onKeyDown={e => e.key === "Enter" && run()} placeholder={t("assistantPlaceholder")}/><button className="gold-btn full" onClick={run}>{t("search")}</button>{results.slice(0, 4).map(p => <MiniProduct key={p.id} product={p}/>)}</div>}</div>; }

function AppContent() { const { t } = useLang(); return <ErrorBoundary t={t}><Shell><Routes><Route path="/" element={<Home/>}/><Route path="/login" element={<Login/>}/><Route path="/role" element={<Role/>}/><Route path="/explore" element={<Explore/>}/><Route path="/search" element={<Explore/>}/><Route path="/product/:id" element={<ProductDetails/>}/><Route path="/artisan/:id" element={<ArtisanProfile/>}/><Route path="/artisans" element={<Artisans/>}/><Route path="/heritage" element={<Heritage/>}/><Route path="/craft-map" element={<Heritage/>}/><Route path="/crafts" element={<Explore/>}/><Route path="/stories" element={<Stories/>}/><Route path="/events" element={<Events/>}/><Route path="/impact" element={<Impact/>}/><Route path="/notifications" element={<Notifications/>}/><Route path="/wishlist" element={<Wishlist/>}/><Route path="/cart" element={<Cart/>}/><Route path="/orders" element={<BuyerOrders/>}/><Route path="/rewards" element={<Rewards/>}/><Route path="/about" element={<About/>}/><Route path="/help" element={<SimplePage title="help"/>}/><Route path="/contact" element={<SimplePage title="contact"/>}/><Route path="/privacy" element={<SimplePage title="privacy"/>}/><Route path="/terms" element={<SimplePage title="terms"/>}/><Route path="/seller" element={<SellerDashboard/>}/><Route path="/seller/products" element={<SellerProducts/>}/><Route path="/seller/products/new" element={<ProductStudio/>}/><Route path="/seller/product-studio" element={<ProductStudio/>}/><Route path="/seller/orders" element={<SellerOrders/>}/><Route path="/seller/inventory" element={<Inventory/>}/><Route path="/seller/analytics" element={<Analytics/>}/><Route path="/seller/photo-studio" element={<PhotoStudio/>}/><Route path="/seller/enquiries" element={<SellerAnalyticsPlaceholder active="enquiries" title="enquiries" icon={Bell}/>}/><Route path="/seller/market" element={<SellerAnalyticsPlaceholder active="market" title="market" icon={Compass}/>}/><Route path="/seller/profile" element={<Profile/>}/><Route path="/seller/settings" element={<SettingsPage/>}/><Route path="/seller/verification" element={<Verification/>}/><Route path="*" element={<NotFound/>}/></Routes></Shell></ErrorBoundary>; }

export default function App() {
  useEffect(() => {
    const onImageError = (event) => {
      const img = event.target;
      if (!(img instanceof HTMLImageElement) || img.dataset.kalaudaanFallback === "1") return;
      img.dataset.kalaudaanFallback = "1";
      img.src = OFFLINE_IMAGE;
    };
    window.addEventListener("error", onImageError, true);
    return () => window.removeEventListener("error", onImageError, true);
  }, []);

  return <LangProvider><AppContent /></LangProvider>;
}
